services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "6070:6070"
    volumes:
      - ./config/Caddyfile.local:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - TZ=UTC

  zoekt-indexserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanchaya-zoekt-indexer
    command: ["zoekt-indexserver", "-data_dir", "/data", "-index_dir", "/data/index"]
    volumes:
      - ./data/index:/data/index
      - ./data/repos:/data/repos
    restart: unless-stopped
    ports:
      - "6072:6072"
    environment:
      - TZ=UTC

  zoekt-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanchaya-zoekt-web
    command: ["zoekt-webserver", "-listen", "0.0.0.0:6070", "-index", "/data/index", "-template_dir", "/app/config/templates"]
    volumes:
      - ./data/index:/data/index
      - ./config/templates:/app/config/templates
    restart: unless-stopped
    # We'll remove the port binding here since Caddy will handle it
    # This prevents the port conflict on your local machine
    depends_on:
      - zoekt-indexserver
    environment:
      - TZ=UTC

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanchaya-zoekt-indexer-run
    # command: ["/bin/bash", "-c", "git clone https://github.com/cahcblr/sanchaya /data/repos/sanchaya || (cd /data/repos/sanchaya && git pull) && zoekt-git-index -index=/data/index -repo_cache=/data/repos -require_ctags=false -incremental -branch main /data/repos/sanchaya"]
    command: ["/bin/bash", "-c", "git clone https://github.com/cahcblr/sanchaya.git /data/repos/sanchaya || (cd /data/repos/sanchaya && git pull) && zoekt-git-index -index=/data/index -repo_cache=/data/repos -file_limit 35984136 -require_ctags=false -branches main /data/repos/sanchaya"]
    volumes:
      - ./data/index:/data/index
      - ./data/repos:/data/repos
    restart: "no"
    depends_on:
      - zoekt-indexserver
    environment:
      - TZ=UTC

volumes:
  caddy_data:
  caddy_config:
