services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "6070:6070"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - TZ=UTC

  zoekt-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanchaya-zoekt-web
    container_name: zoekt-webserver
    command: ["zoekt-webserver", "-listen", "0.0.0.0:6070", "-index", "/data/index", "-template_dir", "/app/config/templates"]
    volumes:
      - ./data/index:/data/index
      - ./config/templates:/app/config/templates
    restart: unless-stopped
    depends_on:
      - caddy
    environment:
      - TZ=UTC

  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    image: sanchaya-zoekt-indexer-run
    command: ["/bin/bash", "-c", "git clone https://github.com/cahcblr/sanchaya.git /data/repos/sanchaya || (cd /data/repos/sanchaya && git pull) && zoekt-git-index -index=/data/index -repo_cache=/data/repos -file_limit 40000000 -max_trigram_count 2000000 -shard_limit 200000000 -parallelism 8 -large_file \"*.txt\" -require_ctags=false -branches main /data/repos/sanchaya"]
    volumes:
      - ./data/index:/data/index
      - ./data/repos:/data/repos
    restart: "no"
    depends_on:
      - zoekt-webserver
    environment:
      - TZ=UTC

volumes:
  caddy_data:
  caddy_config:
